### ISSUE TITLE
As A developer, I WANT to see a search box appear on the page, SO THAT i can input a search request

### ISSUE THREAD

**Issue by c-navarroperez** [c-navarroperez/fetchbook#2]
Acceptance Criteria:

GIVEN a search criteria entered into the search box
WHEN the submit button is used
THEN the search criteria is displayed in the console.log

**Comment by SimonStoneman** [comment]
Html for search input area added and now merged with main

**Comment by BritishCryptoGuy** [comment]
A search box does appear on the page and can have search requests inputted into it. Good job all
